### ISSUE TITLE
Canno register new user

### ISSUE THREAD

**Issue by gmag11** [anasjaber/mongo-explorer#1]
Hi,

I've installed mongo-explorer as a docker compose. This is the yaml file:

```
services:
  backend:
    container_name: mongoeplorer_backend
    build:
      context: ./image/backend
      dockerfile: Dockerfile
    image: tinygs/mongoexplorer_backend
    ports:
      - "${TS_ADDR}:7073:7073"
    environment:
      - ASPNETCORE_URLS=http://+:7073
      - ALLOWED_ORIGINS=http://${TS_ADDR}:7072,http://localhost:7072
      - USE_HTTPS=false
      - ConnectionStrings__DefaultConnection=Data Source=/app/data/MongoConnectionManager.db
    volumes:
      - ./backend-data:/app/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7073/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  frontend:
    build:
      context: ./image/frontend
      dockerfile: Dockerfile
      args:
        - REACT_APP_API_BASE_URL=http://backend:7073/api
    image: tinygs/mongoexplorer_frontend
    ports:
      - "${TS_ADDR}:7072:7072"
    depends_on:
      backend:
        condition: service_healthy
```

When I try to register a new user I get this error:
```
Registration failed
An error occurred. Please check your details and try again.
```

How can I make debug level higher so that I can get more info on what is happening?

Regards
